
import React from 'react';

// One Generate click fills the whole week: POSTS_PER_DAY × WEEKDAYS = 15 posts.
// We make ONE API call per weekday (5 sequential calls), each producing
// POSTS_PER_DAY posts on different topics. Each call avoids topics already
// generated by earlier calls so the full 15 are subject-distinct.
export const POSTS_PER_DAY = 3;
export const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
export const IMAGE_COUNT = POSTS_PER_DAY * WEEKDAYS.length; // 15 — total cards/posts per click

// ─── RENDER FORMATTED POST TEXT ───
export function FormattedPost({ text }) {
  if (!text) return null;
  const lines = text.split('\n');
  const elements = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '') { elements.push(<div key={i} className="h-2" />); continue; }
    const bulletMatch = line.match(/^\s*([\u2192\u2022\-\*]|\d+[\.\)])\s+(.*)/);
    if (bulletMatch) {
      const marker = bulletMatch[1];
      const content = bulletMatch[2];
      elements.push(
        <div key={i} className="flex items-start gap-2 pl-2 py-0.5">
          <span className="text-blue-500 font-bold shrink-0 mt-0.5">{marker === '-' || marker === '*' ? '\u2192' : marker}</span>
          <span>{renderInline(content)}</span>
        </div>
      );
      continue;
    }
    elements.push(<p key={i} className="py-0.5">{renderInline(line)}</p>);
  }
  return <>{elements}</>;
}

function renderInline(text) {
  if (!text) return text;
  const parts = [];
  let remaining = text;
  let key = 0;
  while (remaining.length > 0) {
    const boldMatch = remaining.match(/\*\*(.+?)\*\*/);
    if (boldMatch) {
      const idx = remaining.indexOf(boldMatch[0]);
      if (idx > 0) parts.push(<span key={key++}>{remaining.substring(0, idx)}</span>);
      parts.push(<strong key={key++} className="font-bold text-[var(--text-3)]">{boldMatch[1]}</strong>);
      remaining = remaining.substring(idx + boldMatch[0].length);
      continue;
    }
    parts.push(<span key={key++}>{remaining}</span>);
    break;
  }
  return parts.length === 1 ? parts[0] : parts;
}

// ─── ENGAGEMENT BADGE ───
export function EngagementBadge({ level }) {
  const colors = { viral: 'bg-red-500', high: 'bg-orange-500', medium: 'bg-yellow-500' };
  return (
    <span className={`text-xs px-2 py-0.5 rounded-full text-white font-medium ${colors[level] || 'bg-gray-500'}`}>
      {level === 'viral' ? '\uD83D\uDD25 Viral' : level === 'high' ? '\u26A1 High' : '\uD83D\uDCC8 Medium'}
    </span>
  );
}

// ═══════════ POST → CARD CONTENT EXTRACTION ═══════════
// Parse the actual generated post into facets (topic, hook, bullets, numbers,
// closing) so the branded cards reflect THIS post — not a hardcoded set.
const HASHTAG_RX = /#\w+/g;
const NUM_RX = /(\$?\d[\d,]*(?:\.\d+)?[KMB]?%?\+?)/g;
const BULLET_RX = /^\s*([\u2192\u2022\u25BA\u25CF\-\*])\s+(.*)/;
const NUMBERED_RX = /^\s*(\d+[\.\)])\s+(.*)/;

// Strip markdown markers that LLMs leak into post text so they don't end up
// rendered literally on the canvas (e.g. **bold**, *italic*, __underline__,
// `code`, and "Label:" leading boldified labels).
function stripMarkdown(s) {
  if (!s) return '';
  let out = String(s);
  // Triple backticks / fenced code
  out = out.replace(/```[\s\S]*?```/g, ' ');
  // Inline code
  out = out.replace(/`([^`]+)`/g, '$1');
  // Bold/italic asterisks and underscores (greedy strip)
  out = out.replace(/\*\*([^*]+)\*\*/g, '$1');
  out = out.replace(/\*([^*]+)\*/g, '$1');
  out = out.replace(/__([^_]+)__/g, '$1');
  out = out.replace(/_([^_]+)_/g, '$1');
  // Stray asterisks/underscores
  out = out.replace(/[*_]+/g, '');
  // Markdown links [text](url) \u2192 text
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1');
  // Headings/quote markers at line start
  out = out.replace(/^[#>]+\s*/gm, '');
  // Collapse whitespace
  out = out.replace(/[ \t]+/g, ' ').trim();
  return out;
}

function shortenWords(s, max) {
  if (!s) return '';
  const cleaned = stripMarkdown(String(s)).trim();
  const w = cleaned.split(/\s+/);
  if (w.length <= max) return w.join(' ');
  return w.slice(0, max).join(' ') + '\u2026';
}

// Detect lines that are made up only of hashtag-style or CamelCase tag words
// (with or without a leading '#'). The model sometimes drops bare tag tokens
// like "DataEngineering Lakehouse" or just "DataEngineering"
// alone on a line — these are pillar/audience labels meant for our internal
// tracking, not for display on the card. Drop them before they reach the
// closing-line, hook, or subtitle of any card.
function isOnlyTagsLine(line) {
  const t = String(line || '').trim();
  if (!t || t.length < 4) return false;
  const tokens = t.split(/\s+/);
  return tokens.every((tok) => {
    const stripped = tok.replace(/^#+/, '').replace(/[.,;:!?]+$/, '');
    if (stripped.length < 4) return false;
    // CamelCase compound: starts with capital, no spaces, only letters/digits.
    return /^[A-Z][a-zA-Z0-9]*$/.test(stripped);
  });
}

export function parseStatLine(line) {
  const s = String(line || '').trim();
  const m = s.match(/^([\$\d,\.%\+]+[KMB]?%?)\s*(.*)/);
  if (m && m[1]) return { stat: m[1], label: (m[2] || '').trim() || s };
  return { stat: shortenWords(s, 1) || 'Insight', label: shortenWords(s, 14) };
}

export function extractPostFacets(postText, trending, topicHint) {
  const fallbackTopic = (trending && trending.topic) || topicHint || 'Insight';
  if (!postText) {
    return {
      topic: fallbackTopic,
      topicLabel: String(fallbackTopic).toUpperCase(),
      hook: '',
      paragraphs: [],
      bullets: [],
      sentences: [],
      numericFacts: [],
      closing: '',
    };
  }
  // Strip markdown FIRST so headlines/bullets don't render literal ** or _
  const raw = stripMarkdown(String(postText)).trim();
  const linesAll = raw.split('\n').map((l) => l.replace(HASHTAG_RX, '').trim());
  // Drop empty lines AND tag-only lines (bare CamelCase pillar/audience labels).
  const lines = linesAll.filter((l) => l.length > 0 && !isOnlyTagsLine(l));

  const bullets = [];
  const paragraphs = [];
  for (const l of lines) {
    const bm = l.match(BULLET_RX);
    const nm = l.match(NUMBERED_RX);
    if (bm) bullets.push(bm[2].trim());
    else if (nm) bullets.push(nm[2].trim());
    else paragraphs.push(l);
  }

  const hook = paragraphs[0] || bullets[0] || lines[0] || '';
  const closing = paragraphs[paragraphs.length - 1] || bullets[bullets.length - 1] || hook;

  const sentences = [];
  for (const p of paragraphs) {
    const parts = p.split(/(?<=[.!?])\s+/).map((x) => x.trim()).filter((x) => x.length > 4);
    for (const s of parts) sentences.push(s);
  }

  const numericFacts = [];
  const seen = new Set();
  for (const l of lines) {
    const nums = l.match(NUM_RX) || [];
    for (const n of nums) {
      if (n.length < 2 && !/[KMB%$]/.test(n)) continue;
      if (seen.has(n)) continue;
      seen.add(n);
      const label = l.replace(n, '').replace(/\s+/g, ' ').trim();
      numericFacts.push({ stat: n, label: shortenWords(label, 14) || hook || fallbackTopic });
      if (numericFacts.length >= 8) break;
    }
    if (numericFacts.length >= 8) break;
  }

  let topic = fallbackTopic;
  if (!trending && !topicHint) topic = shortenWords(hook, 6) || fallbackTopic;
  const topicLabel = String(topic).toUpperCase();

  return { topic, topicLabel, hook, paragraphs, bullets, sentences, numericFacts, closing };
}

export function buildQuoteSlides(facets) {
  const { hook, bullets, sentences, closing, topicLabel } = facets;
  // Pool of distinct, punchy candidates (≤22 words each)
  const pool = [hook, ...sentences, ...bullets, closing]
    .map((s) => String(s || '').trim())
    .filter((s) => s.length >= 8 && s.split(/\s+/).length <= 22)
    .filter((s, i, a) => a.indexOf(s) === i);

  // Build 5 picks with no consecutive duplicates. If pool < 5, cycle through it.
  const picks = [];
  for (let i = 0; i < 5; i++) {
    if (pool.length > 0) picks.push(pool[i % pool.length]);
    else picks.push(hook || topicLabel || 'Insight');
  }

  // Each slide gets a DIFFERENT supporting line so cards don't repeat.
  const support = [...bullets, ...sentences]
    .map((s) => String(s || '').trim())
    .filter((s) => s.length >= 8 && s.split(/\s+/).length <= 22)
    .filter((s, i, a) => a.indexOf(s) === i);

  return picks.map((q, i) => {
    // Find a supporting line that isn't the same as the quote
    let supporting = '';
    for (let k = 0; k < support.length; k++) {
      const cand = support[(i + k) % support.length];
      if (cand && cand !== q) { supporting = cand; break; }
    }
    return {
      quote: shortenWords(q, 12),
      context: shortenWords(supporting, 16),
      closing: shortenWords(closing || hook || '', 8),
    };
  });
}

export function buildMultiSlides(facets, count) {
  const { topicLabel, hook, paragraphs, bullets, sentences, numericFacts, closing } = facets;
  // Pool of unique short content lines we can pull from across slides.
  // Bullets first (they're already punchy), then sentences, then paragraphs.
  const pool = [...bullets, ...sentences, ...paragraphs]
    .map((s) => stripPlainText(s))
    .filter((s) => s && s.length >= 8)
    .filter((s, i, a) => a.indexOf(s) === i);
  const pickFrom = (i) => pool.length ? pool[i % pool.length] : (hook || closing || 'Insight');

  // Slide 1 \u2014 Hook / topic header
  const s1 = {
    topic: topicLabel || 'INSIGHT',
    title: shortenWords(hook || pickFrom(0), 8),
    sub: shortenWords(pickFrom(1), 14),
    subSub: '',
  };

  // Slide 2 \u2014 A stat (if any) OR a different framing
  let s2;
  if (numericFacts.length > 0) {
    const nf = numericFacts[0];
    s2 = {
      topic: 'BY THE NUMBERS',
      title: nf.stat,
      sub: shortenWords(nf.label, 14),
      subSub: numericFacts[1] ? shortenWords(numericFacts[1].stat + ': ' + numericFacts[1].label, 12) : '',
    };
  } else {
    s2 = {
      topic: 'WHY IT MATTERS',
      title: shortenWords(pickFrom(2), 8),
      sub: shortenWords(pickFrom(3), 14),
      subSub: '',
    };
  }

  // Slide 3 & 4 \u2014 bullets if available, otherwise different content cuts
  let s3, s4;
  if (bullets.length >= 2) {
    const half = Math.ceil(bullets.length / 2);
    s3 = { topic: 'KEY POINTS', title: 'What matters:', points: bullets.slice(0, half).map((b) => shortenWords(b, 12)) };
    s4 = { topic: 'AND THEN', title: 'And then:', points: bullets.slice(half).map((b) => shortenWords(b, 12)) };
  } else if (bullets.length === 1) {
    s3 = { topic: 'KEY POINT', title: shortenWords(bullets[0], 10), sub: shortenWords(pickFrom(4), 14), subSub: '' };
    s4 = { topic: 'CONTEXT', title: shortenWords(pickFrom(5), 10), sub: shortenWords(pickFrom(6), 14), subSub: '' };
  } else {
    s3 = { topic: 'CONTEXT', title: shortenWords(pickFrom(2), 10), sub: shortenWords(pickFrom(3), 14), subSub: '' };
    s4 = { topic: 'INSIGHT', title: shortenWords(pickFrom(4), 10), sub: shortenWords(pickFrom(5), 14), subSub: '' };
  }

  // Slide 5 \u2014 Closing CTA
  const s5 = {
    topic: 'THE TAKEAWAY',
    title: shortenWords(closing || hook || pickFrom(7), 10),
    sub: '',
    subSub: '',
  };

  const slides = [s1, s2, s3, s4, s5];

  // Final pass: if any slide ended up identical to a previous one, vary it.
  const seenTitles = new Set();
  for (let i = 0; i < slides.length; i++) {
    const sl = slides[i];
    const key = (sl.title || '') + '|' + (sl.points || []).join('|');
    if (seenTitles.has(key)) {
      // Replace title with a different pool entry
      sl.title = shortenWords(pickFrom(7 + i), 10);
    }
    seenTitles.add(key);
  }

  while (slides.length < count) slides.push(slides[slides.length - 1]);
  return slides.slice(0, count);
}

// Helper used only inside buildMultiSlides \u2014 strip leading bullet markers if any.
function stripPlainText(s) {
  if (!s) return '';
  return String(s).replace(/^[\s\u2192\u2022\u25ba\u25cf\-\*]+\s*/, '').replace(/^\d+[\.\)]\s*/, '').trim();
}

