import { useState, useRef, useEffect } from 'react';
import { callOpenRouter, callOpenRouterMultiPost, fetchTrendingTopics, buildSystemPrompt, buildUserPrompt, FRIDAY_POST_TYPES } from '../utils/openrouter';
import { generateStatCard, generateQuoteCard, generateMultiCard } from '../utils/imageGenerator';
import { MOCK_POSTS } from '../presets/mockPosts';

// One Generate click fills the whole week: POSTS_PER_DAY × WEEKDAYS = 15 posts.
// We make ONE API call per weekday (5 sequential calls), each producing
// POSTS_PER_DAY posts on different topics. Each call avoids topics already
// generated by earlier calls so the full 15 are subject-distinct.
const POSTS_PER_DAY = 3;
const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
const IMAGE_COUNT = POSTS_PER_DAY * WEEKDAYS.length; // 15 — total cards/posts per click

// ─── RENDER FORMATTED POST TEXT ───
function FormattedPost({ text }) {
  if (!text) return null;
  const lines = text.split('\n');
  const elements = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '') { elements.push(<div key={i} className="h-2" />); continue; }
    const bulletMatch = line.match(/^\s*([\u2192\u2022\-\*]|\d+[\.\)])\s+(.*)/);
    if (bulletMatch) {
      const marker = bulletMatch[1];
      const content = bulletMatch[2];
      elements.push(
        <div key={i} className="flex items-start gap-2 pl-2 py-0.5">
          <span className="text-blue-500 font-bold shrink-0 mt-0.5">{marker === '-' || marker === '*' ? '\u2192' : marker}</span>
          <span>{renderInline(content)}</span>
        </div>
      );
      continue;
    }
    elements.push(<p key={i} className="py-0.5">{renderInline(line)}</p>);
  }
  return <>{elements}</>;
}

function renderInline(text) {
  if (!text) return text;
  const parts = [];
  let remaining = text;
  let key = 0;
  while (remaining.length > 0) {
    const boldMatch = remaining.match(/\*\*(.+?)\*\*/);
    if (boldMatch) {
      const idx = remaining.indexOf(boldMatch[0]);
      if (idx > 0) parts.push(<span key={key++}>{remaining.substring(0, idx)}</span>);
      parts.push(<strong key={key++} className="font-bold text-gray-900">{boldMatch[1]}</strong>);
      remaining = remaining.substring(idx + boldMatch[0].length);
      continue;
    }
    parts.push(<span key={key++}>{remaining}</span>);
    break;
  }
  return parts.length === 1 ? parts[0] : parts;
}

// ─── ENGAGEMENT BADGE ───
function EngagementBadge({ level }) {
  const colors = { viral: 'bg-red-500', high: 'bg-orange-500', medium: 'bg-yellow-500' };
  return (
    <span className={`text-xs px-2 py-0.5 rounded-full text-white font-medium ${colors[level] || 'bg-gray-500'}`}>
      {level === 'viral' ? '\uD83D\uDD25 Viral' : level === 'high' ? '\u26A1 High' : '\uD83D\uDCC8 Medium'}
    </span>
  );
}

// ═══════════ POST → CARD CONTENT EXTRACTION ═══════════
// Parse the actual generated post into facets (topic, hook, bullets, numbers,
// closing) so the branded cards reflect THIS post — not a hardcoded set.
const HASHTAG_RX = /#\w+/g;
const NUM_RX = /(\$?\d[\d,]*(?:\.\d+)?[KMB]?%?\+?)/g;
const BULLET_RX = /^\s*([\u2192\u2022\u25BA\u25CF\-\*])\s+(.*)/;
const NUMBERED_RX = /^\s*(\d+[\.\)])\s+(.*)/;

// Strip markdown markers that LLMs leak into post text so they don't end up
// rendered literally on the canvas (e.g. **bold**, *italic*, __underline__,
// `code`, and "Label:" leading boldified labels).
function stripMarkdown(s) {
  if (!s) return '';
  let out = String(s);
  // Triple backticks / fenced code
  out = out.replace(/```[\s\S]*?```/g, ' ');
  // Inline code
  out = out.replace(/`([^`]+)`/g, '$1');
  // Bold/italic asterisks and underscores (greedy strip)
  out = out.replace(/\*\*([^*]+)\*\*/g, '$1');
  out = out.replace(/\*([^*]+)\*/g, '$1');
  out = out.replace(/__([^_]+)__/g, '$1');
  out = out.replace(/_([^_]+)_/g, '$1');
  // Stray asterisks/underscores
  out = out.replace(/[*_]+/g, '');
  // Markdown links [text](url) \u2192 text
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1');
  // Headings/quote markers at line start
  out = out.replace(/^[#>]+\s*/gm, '');
  // Collapse whitespace
  out = out.replace(/[ \t]+/g, ' ').trim();
  return out;
}

function shortenWords(s, max) {
  if (!s) return '';
  const cleaned = stripMarkdown(String(s)).trim();
  const w = cleaned.split(/\s+/);
  if (w.length <= max) return w.join(' ');
  return w.slice(0, max).join(' ') + '\u2026';
}

// Detect lines that are made up only of hashtag-style or CamelCase tag words
// (with or without a leading '#'). The model sometimes drops bare tag tokens
// like "HospitalLeadership PhysicianShortage" or just "HospitalLeadership"
// alone on a line — these are pillar/audience labels meant for our internal
// tracking, not for display on the card. Drop them before they reach the
// closing-line, hook, or subtitle of any card.
function isOnlyTagsLine(line) {
  const t = String(line || '').trim();
  if (!t || t.length < 4) return false;
  const tokens = t.split(/\s+/);
  return tokens.every((tok) => {
    const stripped = tok.replace(/^#+/, '').replace(/[.,;:!?]+$/, '');
    if (stripped.length < 4) return false;
    // CamelCase compound: starts with capital, no spaces, only letters/digits.
    return /^[A-Z][a-zA-Z0-9]*$/.test(stripped);
  });
}

function parseStatLine(line) {
  const s = String(line || '').trim();
  const m = s.match(/^([\$\d,\.%\+]+[KMB]?%?)\s*(.*)/);
  if (m && m[1]) return { stat: m[1], label: (m[2] || '').trim() || s };
  return { stat: shortenWords(s, 1) || 'Insight', label: shortenWords(s, 14) };
}

function extractPostFacets(postText, trending, topicHint) {
  const fallbackTopic = (trending && trending.topic) || topicHint || 'Insight';
  if (!postText) {
    return {
      topic: fallbackTopic,
      topicLabel: String(fallbackTopic).toUpperCase(),
      hook: '',
      paragraphs: [],
      bullets: [],
      sentences: [],
      numericFacts: [],
      closing: '',
    };
  }
  // Strip markdown FIRST so headlines/bullets don't render literal ** or _
  const raw = stripMarkdown(String(postText)).trim();
  const linesAll = raw.split('\n').map((l) => l.replace(HASHTAG_RX, '').trim());
  // Drop empty lines AND tag-only lines (bare CamelCase pillar/audience labels).
  const lines = linesAll.filter((l) => l.length > 0 && !isOnlyTagsLine(l));

  const bullets = [];
  const paragraphs = [];
  for (const l of lines) {
    const bm = l.match(BULLET_RX);
    const nm = l.match(NUMBERED_RX);
    if (bm) bullets.push(bm[2].trim());
    else if (nm) bullets.push(nm[2].trim());
    else paragraphs.push(l);
  }

  const hook = paragraphs[0] || bullets[0] || lines[0] || '';
  const closing = paragraphs[paragraphs.length - 1] || bullets[bullets.length - 1] || hook;

  const sentences = [];
  for (const p of paragraphs) {
    const parts = p.split(/(?<=[.!?])\s+/).map((x) => x.trim()).filter((x) => x.length > 4);
    for (const s of parts) sentences.push(s);
  }

  const numericFacts = [];
  const seen = new Set();
  for (const l of lines) {
    const nums = l.match(NUM_RX) || [];
    for (const n of nums) {
      if (n.length < 2 && !/[KMB%$]/.test(n)) continue;
      if (seen.has(n)) continue;
      seen.add(n);
      const label = l.replace(n, '').replace(/\s+/g, ' ').trim();
      numericFacts.push({ stat: n, label: shortenWords(label, 14) || hook || fallbackTopic });
      if (numericFacts.length >= 8) break;
    }
    if (numericFacts.length >= 8) break;
  }

  let topic = fallbackTopic;
  if (!trending && !topicHint) topic = shortenWords(hook, 6) || fallbackTopic;
  const topicLabel = String(topic).toUpperCase();

  return { topic, topicLabel, hook, paragraphs, bullets, sentences, numericFacts, closing };
}

function buildQuoteSlides(facets) {
  const { hook, bullets, sentences, closing, topicLabel } = facets;
  // Pool of distinct, punchy candidates (≤22 words each)
  const pool = [hook, ...sentences, ...bullets, closing]
    .map((s) => String(s || '').trim())
    .filter((s) => s.length >= 8 && s.split(/\s+/).length <= 22)
    .filter((s, i, a) => a.indexOf(s) === i);

  // Build 5 picks with no consecutive duplicates. If pool < 5, cycle through it.
  const picks = [];
  for (let i = 0; i < 5; i++) {
    if (pool.length > 0) picks.push(pool[i % pool.length]);
    else picks.push(hook || topicLabel || 'Insight');
  }

  // Each slide gets a DIFFERENT supporting line so cards don't repeat.
  const support = [...bullets, ...sentences]
    .map((s) => String(s || '').trim())
    .filter((s) => s.length >= 8 && s.split(/\s+/).length <= 22)
    .filter((s, i, a) => a.indexOf(s) === i);

  return picks.map((q, i) => {
    // Find a supporting line that isn't the same as the quote
    let supporting = '';
    for (let k = 0; k < support.length; k++) {
      const cand = support[(i + k) % support.length];
      if (cand && cand !== q) { supporting = cand; break; }
    }
    return {
      quote: shortenWords(q, 12),
      context: shortenWords(supporting, 16),
      closing: shortenWords(closing || hook || '', 8),
    };
  });
}

function buildMultiSlides(facets, count) {
  const { topicLabel, hook, paragraphs, bullets, sentences, numericFacts, closing } = facets;
  // Pool of unique short content lines we can pull from across slides.
  // Bullets first (they're already punchy), then sentences, then paragraphs.
  const pool = [...bullets, ...sentences, ...paragraphs]
    .map((s) => stripPlainText(s))
    .filter((s) => s && s.length >= 8)
    .filter((s, i, a) => a.indexOf(s) === i);
  const pickFrom = (i) => pool.length ? pool[i % pool.length] : (hook || closing || 'Insight');

  // Slide 1 \u2014 Hook / topic header
  const s1 = {
    topic: topicLabel || 'INSIGHT',
    title: shortenWords(hook || pickFrom(0), 8),
    sub: shortenWords(pickFrom(1), 14),
    subSub: '',
  };

  // Slide 2 \u2014 A stat (if any) OR a different framing
  let s2;
  if (numericFacts.length > 0) {
    const nf = numericFacts[0];
    s2 = {
      topic: 'BY THE NUMBERS',
      title: nf.stat,
      sub: shortenWords(nf.label, 14),
      subSub: numericFacts[1] ? shortenWords(numericFacts[1].stat + ': ' + numericFacts[1].label, 12) : '',
    };
  } else {
    s2 = {
      topic: 'WHY IT MATTERS',
      title: shortenWords(pickFrom(2), 8),
      sub: shortenWords(pickFrom(3), 14),
      subSub: '',
    };
  }

  // Slide 3 & 4 \u2014 bullets if available, otherwise different content cuts
  let s3, s4;
  if (bullets.length >= 2) {
    const half = Math.ceil(bullets.length / 2);
    s3 = { topic: 'KEY POINTS', title: 'What matters:', points: bullets.slice(0, half).map((b) => shortenWords(b, 12)) };
    s4 = { topic: 'AND THEN', title: 'And then:', points: bullets.slice(half).map((b) => shortenWords(b, 12)) };
  } else if (bullets.length === 1) {
    s3 = { topic: 'KEY POINT', title: shortenWords(bullets[0], 10), sub: shortenWords(pickFrom(4), 14), subSub: '' };
    s4 = { topic: 'CONTEXT', title: shortenWords(pickFrom(5), 10), sub: shortenWords(pickFrom(6), 14), subSub: '' };
  } else {
    s3 = { topic: 'CONTEXT', title: shortenWords(pickFrom(2), 10), sub: shortenWords(pickFrom(3), 14), subSub: '' };
    s4 = { topic: 'INSIGHT', title: shortenWords(pickFrom(4), 10), sub: shortenWords(pickFrom(5), 14), subSub: '' };
  }

  // Slide 5 \u2014 Closing CTA
  const s5 = {
    topic: 'THE TAKEAWAY',
    title: shortenWords(closing || hook || pickFrom(7), 10),
    sub: '',
    subSub: '',
  };

  const slides = [s1, s2, s3, s4, s5];

  // Final pass: if any slide ended up identical to a previous one, vary it.
  const seenTitles = new Set();
  for (let i = 0; i < slides.length; i++) {
    const sl = slides[i];
    const key = (sl.title || '') + '|' + (sl.points || []).join('|');
    if (seenTitles.has(key)) {
      // Replace title with a different pool entry
      sl.title = shortenWords(pickFrom(7 + i), 10);
    }
    seenTitles.add(key);
  }

  while (slides.length < count) slides.push(slides[slides.length - 1]);
  return slides.slice(0, count);
}

// Helper used only inside buildMultiSlides \u2014 strip leading bullet markers if any.
function stripPlainText(s) {
  if (!s) return '';
  return String(s).replace(/^[\s\u2192\u2022\u25ba\u25cf\-\*]+\s*/, '').replace(/^\d+[\.\)]\s*/, '').trim();
}

export default function GeneratePage({ brand, manualKey, selModel, selImgModel, live, showToast, savedPosts, setSavedPosts, radarDraft }) {
  // ─── CORE STATE ───
  const [platform, setPlatform] = useState('LinkedIn');
  const [pillarIdx, setPillarIdx] = useState(0);
  const [audience, setAudience] = useState('');
  const [topic, setTopic] = useState('');
  const [sourceNotes, setSourceNotes] = useState('');

  // Build Radar handoff: when an idea is sent over, pre-fill topic + notes.
  useEffect(() => {
    if (!radarDraft) return;
    setTopic(radarDraft.topic || '');
    setSourceNotes(radarDraft.notes || '');
  }, [radarDraft]);

  // ─── TRENDING TOPICS ───
  const [trendingTopics, setTrendingTopics] = useState([]);
  const [selectedTrending, setSelectedTrending] = useState(null);
  const [trendingLoading, setTrendingLoading] = useState(false);
  const [autoTrending, setAutoTrending] = useState(true);

  // ─── ADVANCED CONTENT CONTROLS ───
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [tone, setTone] = useState('storytelling');
  const [ctaType, setCtaType] = useState('question');
  const [formatting, setFormatting] = useState('balanced');
  const [useEmoji, setUseEmoji] = useState(false);
  const [keywords, setKeywords] = useState('');
  const [keyPhrases, setKeyPhrases] = useState('');
  const [avoidTopics, setAvoidTopics] = useState('');

  // ─── IMAGE STATE ───
  const [imageStyle, setImageStyle] = useState('stat');

  // ─── OUTPUT STATE ───
  // posts[] holds 5 distinct post variations; post is the currently-displayed one
  // (synced with selectedImg so clicking a thumbnail swaps both text and card).
  const [posts, setPosts] = useState([]);
  const [post, setPost] = useState('');
  const [loading, setLoading] = useState(false);
  const [imgLoading, setImgLoading] = useState(false);
  const [bankLoading, setBankLoading] = useState(false);
  const [imgProgress, setImgProgress] = useState('');
  const [error, setError] = useState('');
  const [images, setImages] = useState([]);
  const [selectedImg, setSelectedImg] = useState(0);
  const [genPhase, setGenPhase] = useState('');

  // Sync displayed post with the selected card index so clicking a thumbnail
  // swaps both the post body shown above AND the card.
  useEffect(() => {
    if (posts.length > 0 && posts[selectedImg] !== undefined) {
      setPost(posts[selectedImg]);
    }
  }, [selectedImg, posts]);
  const cvRef = useRef(null);

  const pillar = brand.pillars[pillarIdx] || brand.pillars[0];

  // Em-dash stripper for single-post calls (multi-post calls already strip).
  const stripEmDashesClient = (txt) => {
    if (!txt) return txt;
    let out = String(txt).replace(/\s*[\u2014\u2013]\s*/g, '. ').replace(/\s+--\s+/g, '. ');
    out = out.replace(/\.\s*\./g, '.').replace(/\.\s+([a-z])/g, (_m, c) => '. ' + c.toUpperCase());
    return out.trim();
  };
  const parseList = (str) => str.split(/[,\n]+/).map((s) => s.trim()).filter(Boolean);

  // ─── FETCH TRENDING TOPICS ───
  const loadTrending = async () => {
    if (!live) { showToast('API key required for trending topics'); return; }
    setTrendingLoading(true);
    setTrendingTopics([]);
    setSelectedTrending(null);
    try {
      const topics = await fetchTrendingTopics(manualKey, selModel, brand, pillar, platform, 5);
      setTrendingTopics(topics);
      showToast(`${topics.length} trending topics found!`);
    } catch (e) {
      console.error('[LeadGen] Trending topics failed:', e);
      showToast('Could not fetch trending topics: ' + e.message);
    }
    setTrendingLoading(false);
  };

  // ─── BRANDED CARD GENERATOR (one card per post) ───
  // Each post gets its own card derived from THAT post's content.
  // ctx.slotImageStyle / ctx.slotVariant override the user's UI selection
  // when a fixed schedule is dictating the image system per slot.
  const makeBrandedCard = (postText, cardIndex, totalCards, ctx) => {
    // Text-only posts (e.g. Friday attention posts) skip card generation.
    if (ctx && ctx.noImage) {
      return { url: null, pages: [], textOnly: true, prompt: 'Text-only post (no card)', error: null };
    }
    const cv = cvRef.current;
    if (!cv) return null;
    const slotStyle = (ctx && ctx.slotImageStyle) || imageStyle;
    const slotPillarName = (ctx && ctx.slotPillarName) || pillar.name;
    const variant = (ctx && (ctx.slotVariant === 'light' || ctx.slotVariant === 'dark'))
      ? ctx.slotVariant
      : (cardIndex % 2 === 0 ? 'dark' : 'light');
    const facets = extractPostFacets(postText, ctx && ctx.trending, ctx && ctx.topicHint);
    const dp = brand.dataPoints || [];

    if (slotStyle === 'stat') {
      // Prefer a numeric fact from the post; fall back to brand data point.
      const sl = facets.numericFacts[0]
        || (dp.length ? parseStatLine(dp[cardIndex % dp.length]) : { stat: 'Insight', label: facets.hook || (slotPillarName + ' insights') });
      generateStatCard(cv, {
        stat: sl.stat,
        label: sl.label,
        subtitle: facets.topicLabel ? facets.topicLabel.toLowerCase() : (slotPillarName + ' · ' + (brand.tagline || '')).trim(),
        brandName: brand.name,
        brandColors: brand.colors,
        orientation: 'portrait',
        variant,
      });
      const u = cv.toDataURL('image/png');
      return { url: u, pages: [u], prompt: 'Stat card: ' + (sl.stat + ' ' + sl.label).slice(0, 60), error: null };
    }
    if (slotStyle === 'quote') {
      const quote = shortenWords(facets.hook || facets.topicLabel, 12);
      const context = shortenWords(facets.bullets[0] || facets.sentences[1] || facets.paragraphs[1] || '', 16);
      const closing = shortenWords(facets.closing || facets.hook || '', 8);
      generateQuoteCard(cv, {
        quote, context, closingLine: closing,
        brandName: brand.name,
        brandColors: brand.colors,
        orientation: 'portrait',
        variant,
      });
      const u = cv.toDataURL('image/png');
      return { url: u, pages: [u], prompt: 'Quote card: ' + quote.slice(0, 60), error: null };
    }
    // MULTI-SET: render a full 3-page carousel (01/03, 02/03, 03/03) from the
    // post's content. Pages follow a problem -> context -> takeaway arc via
    // buildMultiSlides. Variant alternates per page for visual variety.
    const CAROUSEL_PAGES = 3;
    const slides = buildMultiSlides(facets, CAROUSEL_PAGES);
    const pages = [];
    for (let p = 0; p < CAROUSEL_PAGES; p++) {
      const c = slides[p] || slides[slides.length - 1];
      const pageVariant = p % 2 === 0 ? variant : (variant === 'dark' ? 'light' : 'dark');
      generateMultiCard(cv, {
        cardNumber: String(p + 1),
        totalCards: String(CAROUSEL_PAGES),
        topicLabel: c.topic,
        title: c.title,
        subtitle: c.sub,
        subSubtitle: c.subSub,
        points: c.points,
        closingLine: c.closing,
        brandName: brand.name,
        brandColors: brand.colors,
        orientation: 'portrait',
        variant: pageVariant,
      });
      pages.push(cv.toDataURL('image/png'));
    }
    return { url: pages[0], pages, prompt: 'Carousel (' + CAROUSEL_PAGES + ' pages): ' + facets.topicLabel, error: null };
  };

  // Produce N cards (one per post text). Accepts either a single ctx (applied
  // to every card) or perPostCtx[] (per-post overrides for slotImageStyle,
  // slotVariant, slotPillarName when the schedule dictates them).
  const makeBrandedImagesForPosts = (postTexts, ctx, perPostCtx) => {
    const out = [];
    for (let i = 0; i < postTexts.length; i++) {
      const localCtx = perPostCtx && perPostCtx[i] ? { ...ctx, ...perPostCtx[i] } : ctx;
      const card = makeBrandedCard(postTexts[i], i, postTexts.length, localCtx);
      if (card) out.push(card);
    }
    setImages(out);
    setSelectedImg(0);
    return out;
  };

  // ─── AUTO-SAVE TO ARCHIVE (weekday-balanced) ───
  // Picks the weekday with the fewest existing posts; ties resolve to the
  // earliest weekday (Monday wins if all are empty). This produces a natural
  // Mon\u2192Fri spread: 1st post lands on Monday, 2nd on Tuesday, etc., looping
  // back to the lightest day after Friday.
  // ─── AUTO-SAVE A WHOLE BATCH TO ONE DAY ───
  // All posts in a batch land on the SAME weekday so one Generate click fills
  // a single day's content slot (3 different posts in one day). The target day
  // is the weekday with the fewest existing posts so successive clicks fill
  // Monday, Tuesday, Wednesday, etc. in order.
  // Flatten card objects into a flat array of page image URLs.
  // A multi-set card carries .pages (the full 3-page carousel); stat/quote
  // cards carry a single page. Stored as allImages so the whole carousel
  // travels with the post and downloads together.
  const expandCardPages = (cards) => {
    const all = [];
    (cards || []).forEach((c) => {
      if (!c) return;
      if (Array.isArray(c.pages) && c.pages.length) all.push(...c.pages);
      else if (c.url) all.push(c.url);
    });
    return all;
  };

  const autoSaveBatchToArchive = (postTexts, imgsList, ctx, batchToastSuffix) => {
    if (!postTexts || postTexts.length === 0) return;
    const now = new Date();
    const WD = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
    setSavedPosts((current) => {
      const counts = WD.map((d) => current.filter((p) => p.weekday === d).length);
      const minCount = Math.min(...counts);
      const weekday = WD[counts.indexOf(minCount)];
      const newEntries = postTexts.map((txt, i) => {
        const successImgs = (imgsList[i] || []).filter((img) => img && img.url);
        const pages = expandCardPages(successImgs);
        return {
          id: Date.now() + Math.floor(Math.random() * 1000) + i,
          text: txt,
          platform: ctx.platform,
          pillar: ctx.pillar.name,
          audience: ctx.pillar.audience,
          tone: ctx.tone,
          ctaType: ctx.ctaType,
          trendingTopic: ctx.trendingTopic || null,
          imageStyle: ctx.imageStyle,
          imageMode: 'branded',
          imageData: successImgs[0]?.url || null,
          allImages: pages,
          pageCount: pages.length,
          createdAt: now.toLocaleString(),
          weekday,
          autoSaved: true,
        };
      });
      // Save the chosen weekday so the toast can reference it (closure capture)
      autoSaveBatchToArchive._lastWeekday = weekday;
      return [...current, ...newEntries];
    });
    const wd = autoSaveBatchToArchive._lastWeekday || 'Archive';
    showToast(`Auto-saved ${postTexts.length} posts to ${wd}${batchToastSuffix ? ' ' + batchToastSuffix : ''}`);
  };

  // Backwards-compat wrapper for trending batch (single-post path).
  const autoSaveToArchive = (txt, imgs, ctx) => {
    if (!txt) return;
    autoSaveBatchToArchive([txt], [imgs || []], ctx);
  };

  // ─── SAVE A FULL WEEK TO ARCHIVE (explicit weekday per post) ───
  // Used when a Generate click follows the schedule. Each entry knows its own
  // weekday + slot metadata. Entries are tagged weekFillBatch:true so the
  // NEXT Generate click can replace them (wipes previous week, keeps manual
  // saves and trending-batch saves).
  const autoSaveWeekToArchive = (postTexts, imgsList, weekdays, ctx, slots) => {
    if (!postTexts || postTexts.length === 0) return;
    const now = new Date();
    setSavedPosts((current) => {
      // Drop any prior week-fill batch so this Generate replaces it.
      const kept = current.filter((p) => !p.weekFillBatch);
      const newEntries = postTexts.map((txt, i) => {
        const successImgs = (imgsList[i] || []).filter((img) => img && img.url);
        const pages = expandCardPages(successImgs);
        const slot = (slots && slots[i]) || null;
        return {
          id: Date.now() + Math.floor(Math.random() * 100000) + i,
          text: txt,
          platform: ctx.platform,
          pillar: slot ? slot.pillar : ctx.pillar.name,
          audience: slot ? slot.audience : ctx.pillar.audience,
          tone: ctx.tone,
          ctaType: ctx.ctaType,
          trendingTopic: ctx.trendingTopic || null,
          imageStyle: slot ? slot.imageStyle : ctx.imageStyle,
          imageMode: 'branded',
          imageData: successImgs[0]?.url || null,
          allImages: pages,
          pageCount: pages.length,
          createdAt: now.toLocaleString(),
          weekday: weekdays[i],
          time: slot ? slot.time : null,
          hookFormula: slot ? slot.hookFormula : null,
          imageVariant: slot ? slot.variant : null,
          autoSaved: true,
          weekFillBatch: true,
        };
      });
      return [...kept, ...newEntries];
    });
    const dayCount = new Set(weekdays).size;
    showToast(`Auto-saved ${postTexts.length} posts across ${dayCount} days (replaced previous week)`);
  };

  // ─── CORE GENERATION ───
  // DEFAULT path: ONE click fills the whole week (Mon-Fri × POSTS_PER_DAY = 15 posts).
  // Each weekday is its own API call so it can avoid topics already covered by
  // earlier weekdays (15 distinct subjects, not 15 angles on one).
  // singlePost: when true, only ONE post + ONE card (used by trending batch).
  const runGeneration = async ({ forcedTrending = null, singlePost = false } = {}) => {
    setPosts([]);
    setPost('');
    setImages([]);
    setSelectedImg(0);

    const advancedOpts = { tone, ctaType, useEmoji, formatting };
    const userAvoid = parseList(avoidTopics);
    const baseContentOpts = {
      keywords: parseList(keywords),
      keyPhrases: parseList(keyPhrases),
      trendingTopic: null,
      sourceNotes,
    };

    let activeTrending = forcedTrending || selectedTrending;
    let postTexts = [];
    let postWeekdays = []; // explicit weekday per post (parallel to postTexts)

    if (live) {
      if (!forcedTrending && autoTrending && !selectedTrending && !topic) {
        setGenPhase('Discovering trending topics...');
        try {
          const topics = await fetchTrendingTopics(manualKey, selModel, brand, pillar, platform, 5);
          setTrendingTopics(topics);
          activeTrending = topics.find((t) => t.engagementPotential === 'viral') || topics.find((t) => t.engagementPotential === 'high') || topics[0];
          setSelectedTrending(activeTrending);
        } catch (e) {
          console.warn('[LeadGen] Auto-trending failed, generating without:', e.message);
        }
      }

      if (singlePost) {
        const contentOpts = { ...baseContentOpts, trendingTopic: activeTrending, avoidTopics: userAvoid };
        setGenPhase(activeTrending ? `Writing about: ${activeTrending.topic.substring(0, 50)}...` : 'Generating fresh content...');
        const t = await callOpenRouter(
          manualKey,
          selModel,
          buildSystemPrompt(brand, platform, advancedOpts),
          buildUserPrompt(pillar, audience, topic, brand.dataPoints, imageStyle, { ...contentOpts, brandName: brand.name })
        );
        postTexts = [t];
        // Single-post path uses the existing fewest-weekday logic via batch save below.
        postWeekdays = [];
      } else {
        // SCHEDULE path: each of the 11 fixed slots is its own API call,
        // with that slot's specific pillar/audience/hook formula. The avoid
        // list grows after every slot so all 11 posts cover distinct topics.
        const SCHEDULE = brand.schedule || [];
        if (SCHEDULE.length === 0) {
          throw new Error('No schedule defined for this brand. Add a schedule[] to the preset.');
        }
        // Identify the strongest data slot (Tue 12:00 Workforce Insights) so the
        // trending topic, when present, seeds it instead of the first slot.
        const trendingSlotIdx = SCHEDULE.findIndex((s) => s.day === 'Tuesday' && s.time === '12:00 PM') >= 0
          ? SCHEDULE.findIndex((s) => s.day === 'Tuesday' && s.time === '12:00 PM')
          : 0;
        const collected = [];
        const failedSlots = [];
        const seenTopicHints = [...userAvoid];
        const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
        // FRIDAY: pick 2 DIFFERENT post types from the 5 available types,
        // one per Friday slot (Fri 10am and Fri 12pm). Shuffle so each Generate
        // click rotates which two types land that week.
        const fridaySlotIndices = SCHEDULE.map((s, i) => (s.friday ? i : -1)).filter((i) => i >= 0);
        const FRIDAY_KEYS = Object.keys(FRIDAY_POST_TYPES);
        const shuffledFridayTypes = [...FRIDAY_KEYS].sort(() => Math.random() - 0.5);
        const fridayTypeBySlotIdx = {};
        fridaySlotIndices.forEach((slotIdx, i) => {
          fridayTypeBySlotIdx[slotIdx] = shuffledFridayTypes[i % shuffledFridayTypes.length];
        });
        // Try one slot; retry once after a longer delay if the first attempt fails.
        const tryOnce = async (slot, slotPillar, slotContentOpts) => {
          return await callOpenRouter(
            manualKey,
            selModel,
            buildSystemPrompt(brand, platform, advancedOpts),
            buildUserPrompt(slotPillar, slot.audience, topic, brand.dataPoints, slot.imageStyle, { ...slotContentOpts, brandName: brand.name })
          );
        };
        for (let i = 0; i < SCHEDULE.length; i++) {
          const slot = SCHEDULE[i];
          const slotPillar = brand.pillars.find((p) => p.name === slot.pillar) || pillar;
          setGenPhase(`${slot.day} ${slot.time} \u00B7 ${slot.pillar} (${i + 1}/${SCHEDULE.length})...`);
          const trendingForThisSlot = i === trendingSlotIdx ? activeTrending : null;
          const slotContentOpts = {
            ...baseContentOpts,
            trendingTopic: trendingForThisSlot,
            avoidTopics: seenTopicHints,
            hookFormula: slot.hookFormula,
            fridayPostType: slot.friday ? fridayTypeBySlotIdx[i] : null,
          };
          // Genphase: show Friday post type when applicable so the user sees
          // 'Friday 10:00 AM · Hot Take' instead of generic 'Friday Newsjack'.
          if (slot.friday) {
            const ft = FRIDAY_POST_TYPES[fridayTypeBySlotIdx[i]];
            setGenPhase(`${slot.day} ${slot.time} \u00B7 Friday ${ft ? ft.name : 'Newsjack'} (${i + 1}/${SCHEDULE.length})...`);
          }
          let text = null;
          let lastError = null;
          for (let attempt = 0; attempt < 2; attempt++) {
            try {
              text = await tryOnce(slot, slotPillar, slotContentOpts);
              break;
            } catch (e) {
              lastError = e;
              console.warn('[LeadGen] Slot attempt ' + (attempt + 1) + ' failed:', slot.day, slot.time, e.message);
              if (attempt === 0) {
                setGenPhase(`${slot.day} ${slot.time} \u00B7 retrying after rate-limit/error...`);
                await sleep(2500);
              }
            }
          }
          if (text) {
            const cleanText = stripEmDashesClient(text);
            collected.push({ text: cleanText, slot });
            const hint = String(cleanText || '').split('\n').find((l) => l.trim()) || '';
            if (hint) seenTopicHints.push(hint.replace(/[\*_]/g, '').slice(0, 80));
          } else {
            failedSlots.push({ slot, error: lastError && lastError.message });
            console.error('[LeadGen] Slot FAILED twice, skipping:', slot.day, slot.time, lastError);
          }
          // Small inter-slot delay to dodge OpenRouter per-minute rate limits.
          if (i < SCHEDULE.length - 1) await sleep(800);
        }
        postTexts = collected.map((c) => c.text);
        postWeekdays = collected.map((c) => c.slot.day);
        runGeneration._lastFailedSlots = failedSlots;
        // Keep slot metadata around for card rendering + archive metadata.
        runGeneration._lastSlots = collected.map((c) => c.slot);
      }
    } else {
      // Demo mode: pull mock posts onto the schedule's slots so the layout matches live mode.
      await new Promise((r) => setTimeout(r, 1500));
      const pp = MOCK_POSTS[platform.toLowerCase()] || MOCK_POSTS.linkedin;
      postTexts = [];
      postWeekdays = [];
      const SCHEDULE = brand.schedule || [];
      if (singlePost || SCHEDULE.length === 0) {
        const pl = pp[pillar.name] || pp['Educational'] || Object.values(pp)[0];
        const shuffled = [...pl].sort(() => Math.random() - 0.5);
        const wantedCount = singlePost ? 1 : SCHEDULE.length || IMAGE_COUNT;
        for (let i = 0; i < wantedCount; i++) {
          postTexts.push(shuffled[i % shuffled.length]);
          if (!singlePost) postWeekdays.push((SCHEDULE[i] && SCHEDULE[i].day) || WEEKDAYS[Math.floor(i / POSTS_PER_DAY) % WEEKDAYS.length]);
        }
        if (!singlePost) runGeneration._lastSlots = SCHEDULE.slice(0, postTexts.length);
      } else {
        const usedSlots = [];
        for (let i = 0; i < SCHEDULE.length; i++) {
          const slot = SCHEDULE[i];
          const pl = pp[slot.pillar] || pp['Educational'] || Object.values(pp)[0];
          const candidate = pl[i % pl.length];
          postTexts.push(candidate);
          postWeekdays.push(slot.day);
          usedSlots.push(slot);
        }
        runGeneration._lastSlots = usedSlots;
      }
    }

    setPosts(postTexts);
    setPost(postTexts[0] || '');
    setGenPhase(`Rendering ${postTexts.length} card${postTexts.length > 1 ? 's' : ''}...`);

    const slots = runGeneration._lastSlots || [];
    const perPostCtx = slots.map((slot) => ({
      slotImageStyle: slot.imageStyle,
      slotVariant: slot.variant,
      slotPillarName: slot.pillar,
      noImage: slot.friday === true || slot.imageStyle == null,
    }));
    const imgResults = makeBrandedImagesForPosts(postTexts, { trending: activeTrending, topicHint: topic }, perPostCtx) || [];

    // Save: if we have explicit weekdays (multi-day path), save with each post's
    // own weekday. Otherwise (single-post path) use the fewest-weekday batch logic.
    // imgsList[i] carries ALL pages of the card (3 for carousels, 1 otherwise)
    // so the archive entry's allImages holds the full multi-page set.
    const imgsList = postTexts.map((_, i) => {
      const r = imgResults[i];
      if (!r) return [];
      const pages = (r.pages && r.pages.length) ? r.pages : (r.url ? [r.url] : []);
      return pages.map((url) => ({ url }));
    });
    const ctx = {
      platform,
      pillar,
      tone,
      ctaType,
      trendingTopic: activeTrending?.topic || null,
      imageStyle,
    };
    if (postWeekdays.length === postTexts.length && postWeekdays.length > 0) {
      autoSaveWeekToArchive(postTexts, imgsList, postWeekdays, ctx, slots);
    } else {
      autoSaveBatchToArchive(postTexts, imgsList, ctx);
    }

    // If any slots failed, surface them visibly (not just to console).
    const failed = runGeneration._lastFailedSlots || [];
    if (failed.length > 0) {
      const expected = (brand.schedule && brand.schedule.length) || postTexts.length;
      const list = failed.map((f) => `${f.slot.day} ${f.slot.time} ${f.slot.pillar}`).join(' | ');
      const reasons = failed.filter((f) => f.error).map((f) => f.error).filter((m, i, a) => a.indexOf(m) === i).join('; ');
      const msg = `Generated ${postTexts.length} of ${expected}. ${failed.length} slot${failed.length > 1 ? 's' : ''} failed after retry: ${list}.${reasons ? ' Errors: ' + reasons + '.' : ''} Click Generate again to refill the missing slots.`;
      setError(msg);
      showToast(`Got ${postTexts.length} of ${expected} posts. ${failed.length} slot${failed.length > 1 ? 's' : ''} failed.`);
    } else if (postTexts.length > 0) {
      setError('');
    }

    return { postTexts, imgResults };
  };

  // Backwards-compat alias used by the trending batch loop (one post per topic).
  const runSingleGeneration = ({ forcedTrending = null } = {}) => runGeneration({ forcedTrending, singlePost: true });

  // ─── MAIN GENERATE (N posts × N paired cards, N = IMAGE_COUNT) ───
  const generate = async () => {
    setLoading(true);
    setError('');
    try {
      await runGeneration({ singlePost: false });
    } catch (e) {
      setError(e.message);
    }
    setLoading(false);
    setGenPhase('');
  };

  // ─── BATCH GENERATE (one post per trending topic) ───
  const generateAllTrending = async () => {
    if (!trendingTopics || trendingTopics.length === 0) {
      showToast('No trending topics. Click "Find Now" first.');
      return;
    }
    if (!live) {
      showToast('Live API mode required for batch generation');
      return;
    }
    setLoading(true);
    setError('');
    let count = 0;
    const total = trendingTopics.length;
    for (let i = 0; i < total; i++) {
      setGenPhase(`Batch ${i + 1}/${total}: ${trendingTopics[i].topic.substring(0, 40)}\u2026`);
      try {
        await runSingleGeneration({ forcedTrending: trendingTopics[i] });
        count++;
      } catch (e) {
        console.error('[LeadGen] Batch item failed:', trendingTopics[i].topic, e);
      }
    }
    setLoading(false);
    setGenPhase('');
    showToast(`Batch complete: ${count}/${total} posts auto-saved to Archive`);
  };

  // ─── STATICS BANK ───
  // Batch-generates evergreen posts (not tied to news or builds) straight to
  // Saved. They're the fallback buffer: any week the build doesn't happen,
  // post from the bank and the lane never goes dark.
  const generateStaticsBank = async () => {
    if (!live) { showToast('Add an OpenRouter API key first.'); return; }
    const BANK_SIZE = 8;
    const pillarName = brand.presetId === 'databricks' ? 'Career & Craft' : 'Physician Lifestyle';
    const bankPillar = brand.pillars.find((p) => p.name === pillarName) || brand.pillars[0];
    setBankLoading(true);
    const texts = [];
    const avoid = [];
    try {
      for (let i = 0; i < BANK_SIZE; i++) {
        setGenPhase(`Statics bank ${i + 1}/${BANK_SIZE} · ${bankPillar.name}...`);
        const t = await callOpenRouter(
          manualKey,
          selModel,
          buildSystemPrompt(brand, platform, { tone, ctaType, useEmoji, formatting }),
          buildUserPrompt(bankPillar, bankPillar.audience, 'EVERGREEN post: a timeless lesson, story, or defensible opinion. Must NOT reference current news, dates, or recent events. It should read just as well six months from now.', brand.dataPoints, null, { brandName: brand.name, avoidTopics: avoid })
        );
        texts.push(t);
        avoid.push((t.split('\n').find((l) => l.trim()) || '').slice(0, 120));
        await new Promise((r) => setTimeout(r, 600));
      }
      const now = new Date();
      setSavedPosts((current) => [
        ...current,
        ...texts.map((txt, i) => ({
          id: Date.now() + i,
          text: txt,
          platform,
          pillar: bankPillar.name,
          audience: bankPillar.audience,
          tone,
          ctaType,
          imageStyle: null,
          imageMode: 'branded',
          imageData: null,
          allImages: [],
          pageCount: 0,
          createdAt: now.toLocaleString(),
          staticsBank: true,
        })),
      ]);
      showToast(`Statics bank filled: ${texts.length} evergreen posts in Saved.`);
    } catch (e) {
      showToast(`Statics bank stopped after ${texts.length}: ${e.message}`);
    } finally {
      setBankLoading(false);
      setGenPhase('');
    }
  };

  const savePost = () => {
    // Save the currently-selected post (paired with its card)
    const currentText = posts[selectedImg] || post;
    if (!currentText) return;
    const currentCard = images[selectedImg] || null;
    const currentImg = currentCard?.url || null;
    const pages = expandCardPages(currentCard ? [currentCard] : []);
    const now = new Date();
    const weekdayName = now.toLocaleDateString('en-US', { weekday: 'long' });
    const WD = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
    const weekday = WD.includes(weekdayName) ? weekdayName : 'Monday';
    setSavedPosts((p) => [
      ...p,
      {
        id: Date.now(),
        text: currentText,
        platform,
        pillar: pillar.name,
        audience: pillar.audience,
        tone,
        ctaType,
        trendingTopic: selectedTrending?.topic || null,
        imageStyle,
        imageMode: 'branded',
        imageData: currentImg,
        allImages: pages.length ? pages : (currentImg ? [currentImg] : []),
        pageCount: pages.length || (currentImg ? 1 : 0),
        createdAt: now.toLocaleString(),
        weekday,
      },
    ]);
    showToast('Post saved to Archive!');
  };

  // Download every page of one card object (carousels = 3 pages, else 1).
  const downloadImage = (imgObj, idx) => {
    if (!imgObj) return;
    const pages = (imgObj.pages && imgObj.pages.length) ? imgObj.pages : (imgObj.url ? [imgObj.url] : []);
    if (!pages.length) return;
    const base = `${brand.name || 'post'}-${idx + 1}-${Date.now()}`;
    const multi = pages.length > 1;
    pages.forEach((url, p) => {
      if (!url) return;
      setTimeout(() => {
        const a = document.createElement('a');
        a.download = multi ? `${base}-${String(p + 1).padStart(2, '0')}.png` : `${base}.png`;
        a.href = url;
        a.click();
      }, p * 350);
    });
    showToast(multi ? `Downloading ${pages.length}-page carousel...` : 'Downloaded!');
  };

  const downloadAll = () => {
    let delay = 0;
    let fileCount = 0;
    images.filter((i) => i.url).forEach((img, idx) => {
      const pages = (img.pages && img.pages.length) ? img.pages : [img.url];
      const multi = pages.length > 1;
      pages.forEach((url, p) => {
        if (!url) return;
        fileCount += 1;
        setTimeout(() => {
          const a = document.createElement('a');
          a.download = multi
            ? `${brand.name || 'post'}-${idx + 1}-${String(p + 1).padStart(2, '0')}-${Date.now()}.png`
            : `${brand.name || 'post'}-${idx + 1}-${Date.now()}.png`;
          a.href = url;
          a.click();
        }, delay);
        delay += 300;
      });
    });
    showToast(`Downloading ${fileCount} images (all pages)...`);
  };

  const TONES = [
    { id: 'authoritative', label: 'Authoritative', desc: 'Expert, data-driven' },
    { id: 'conversational', label: 'Conversational', desc: 'Warm, relatable' },
    { id: 'provocative', label: 'Provocative', desc: 'Bold, contrarian' },
    { id: 'storytelling', label: 'Storytelling', desc: 'Narrative-driven' },
    { id: 'educational', label: 'Educational', desc: 'Clear, instructive' },
  ];
  const CTA_TYPES = [
    { id: 'question', label: 'Question', desc: 'Invite comments' },
    { id: 'dm', label: 'DM CTA', desc: 'DM me "GUIDE"' },
    { id: 'link', label: 'Link CTA', desc: 'Point to resource' },
    { id: 'engage', label: 'Engage', desc: 'Share experience' },
    { id: 'none', label: 'None', desc: 'No CTA' },
  ];
  const FORMAT_OPTS = [
    { id: 'minimal', label: 'Minimal', desc: 'Flowing prose' },
    { id: 'balanced', label: 'Balanced', desc: 'Mix of prose & lists' },
    { id: 'heavy', label: 'Structured', desc: 'Bullets & bold' },
  ];
  const IMAGE_STYLES = [
    { id: 'stat', l: '\uD83D\uDCCA Stat Card', d: 'Bold number' },
    { id: 'quote', l: '\uD83D\uDCAC Quote Card', d: 'Perspective' },
    { id: 'multi', l: '\uD83D\uDCD1 Multi-Set', d: '3 images' },
  ];

  const successfulImages = images.filter((i) => i.url);

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-fade-in">
      {/* ═══════════ LEFT: CONTROLS ═══════════ */}
      <div className="space-y-4">
        <div className="card p-5">
          <h2 className="text-lg font-bold text-white mb-4">{'\u26A1'} Generate Content + Images</h2>

          {/* Platform */}
          <div className="flex gap-2 mb-4">
            {['LinkedIn', 'Facebook'].map((p) => (
              <button key={p} className={`flex-1 py-2 rounded-lg text-sm font-semibold transition-all ${platform === p ? 'tab-active' : 'tab-inactive'}`} onClick={() => setPlatform(p)}>
                {p === 'LinkedIn' ? '\uD83D\uDCBC' : '\uD83D\uDC65'} {p}
              </button>
            ))}
          </div>

          {/* Pillar — when a fixed schedule exists, this becomes a reference
              only because each slot's pillar is dictated by the schedule. */}
          <label className="block text-sm font-medium text-gray-300 mb-1">
            Content Pillar
            {brand.schedule && brand.schedule.length > 0 && (
              <span className="text-xs text-amber-300 font-normal ml-2">(schedule overrides: each slot uses its own pillar)</span>
            )}
          </label>
          <select
            className="input-field mb-3"
            value={pillarIdx}
            onChange={(e) => setPillarIdx(Number(e.target.value))}
            disabled={!!(brand.schedule && brand.schedule.length > 0)}
            title={brand.schedule && brand.schedule.length > 0 ? 'Pillar is set per slot by the schedule' : ''}
          >
            {brand.pillars.map((p, i) => (
              <option key={i} value={i}>{`${p.name} (${p.audience})`}</option>
            ))}
          </select>

          {/* Audience */}
          <label className="block text-sm font-medium text-gray-300 mb-1">Target Audience <span className="text-gray-500">(optional)</span></label>
          <input className="input-field mb-3" placeholder={pillar.audience} value={audience} onChange={(e) => setAudience(e.target.value)} />

          {/* ─── TRENDING TOPICS SECTION ─── */}
          <div className="mb-4 p-4 rounded-lg border border-indigo-800 bg-indigo-900 bg-opacity-20">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-sm font-bold text-indigo-300">{'\uD83D\uDD25'} Trending Topics</h3>
              <div className="flex items-center gap-3">
                <label className="flex items-center gap-1.5 text-xs text-gray-400 cursor-pointer">
                  <span>Auto-discover</span>
                  <button
                    className={`relative w-9 h-5 rounded-full transition-all ${autoTrending ? 'bg-indigo-600' : 'bg-gray-700'}`}
                    onClick={() => setAutoTrending(!autoTrending)}
                  >
                    <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all ${autoTrending ? 'left-4' : 'left-0.5'}`} />
                  </button>
                </label>
                <button
                  className="btn-ghost text-xs py-1 px-2"
                  onClick={loadTrending}
                  disabled={trendingLoading || !live}
                >
                  {trendingLoading ? 'Searching...' : '\uD83D\uDD0D Find Now'}
                </button>
              </div>
            </div>

            {!live && <p className="text-xs text-gray-500">Add API key to enable trending topic discovery</p>}

            {autoTrending && live && trendingTopics.length === 0 && !trendingLoading && (
              <p className="text-xs text-indigo-400">Trending topics will be auto-discovered when you generate</p>
            )}

            {trendingLoading && (
              <div className="flex items-center gap-2 py-2">
                <span className="spinner" style={{ width: 16, height: 16 }} />
                <span className="text-xs text-indigo-300">Searching for trending topics in your niche...</span>
              </div>
            )}

            {trendingTopics.length > 0 && (
              <div className="space-y-2 mt-2 max-h-64 overflow-y-auto">
                {trendingTopics.map((t, i) => (
                  <button
                    key={i}
                    className={`w-full text-left p-3 rounded-lg transition-all ${
                      selectedTrending === t
                        ? 'bg-indigo-700 border border-indigo-500'
                        : 'bg-gray-800 bg-opacity-60 border border-gray-700 hover:border-indigo-500'
                    }`}
                    onClick={() => setSelectedTrending(selectedTrending === t ? null : t)}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1">
                        <div className="text-sm font-semibold text-white leading-tight">{t.topic}</div>
                        <div className="text-xs text-gray-400 mt-1">{t.angle}</div>
                      </div>
                      <EngagementBadge level={t.engagementPotential} />
                    </div>
                    <div className="text-xs text-gray-500 mt-1.5">{t.whyTrending}</div>
                    {selectedTrending === t && t.suggestedHook && (
                      <div className="text-xs text-indigo-300 mt-2 pt-2 border-t border-indigo-700">
                        {'\uD83C\uDFA3'} Hook: "{t.suggestedHook}"
                      </div>
                    )}
                  </button>
                ))}
                <button
                  className="w-full py-2 px-3 rounded-lg text-sm font-semibold bg-indigo-600 hover:bg-indigo-500 text-white border border-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                  onClick={generateAllTrending}
                  disabled={loading || imgLoading || !live}
                  title="Generate one full post + 5 images for every trending topic, auto-saved across the week"
                >
                  {'\u26A1\u26A1'} Generate all {trendingTopics.length} as posts (auto-spread Mon\u2192Fri)
                </button>
                <button
                  className="text-xs text-indigo-400 hover:text-indigo-300 w-full text-center py-1"
                  onClick={() => { setSelectedTrending(null); setTrendingTopics([]); }}
                >
                  Clear trending topics (use manual topic instead)
                </button>
              </div>
            )}
          </div>

          {/* Topic (manual - shown when no trending selected) */}
          {!selectedTrending && (
            <>
              <label className="block text-sm font-medium text-gray-300 mb-1">Topic / Angle <span className="text-gray-500">{'(optional, or use trending above)'}</span></label>
              <textarea className="input-field mb-3" placeholder={brand.presetId === 'databricks' ? 'e.g., What the AI data-center buildout looks like in real grid data...' : 'e.g., The hidden cost of reactive physician staffing...'} value={topic} onChange={(e) => setTopic(e.target.value)} rows={2} />
            </>
          )}

          {/* Source notes — real-work material for practitioner posts (Build Log etc.).
              The prompt treats these as the ONLY allowed source of first-person claims. */}
          <label className="block text-sm font-medium text-gray-300 mb-1">
            My notes from real work <span className="text-gray-500">(optional — required for Build Log posts)</span>
          </label>
          <textarea
            className="input-field mb-1"
            placeholder="Paste rough notes from what you actually built: what you made, what broke, the numbers. The post will only claim what's in here."
            value={sourceNotes}
            onChange={(e) => setSourceNotes(e.target.value)}
            rows={3}
          />
          <p className="text-xs text-gray-500 mb-3">Posts never invent first-person experiences. No notes = no "I built this" claims.</p>

          {/* Advanced toggle */}
          <button
            className="w-full flex items-center justify-between py-2.5 px-3 rounded-lg mb-3 text-sm font-medium transition-all bg-gray-800 border border-gray-600 hover:border-gray-500 text-gray-300"
            onClick={() => setShowAdvanced(!showAdvanced)}
          >
            <span>{'\u2699\uFE0F'} Advanced Content Options</span>
            <span className={`transition-transform ${showAdvanced ? 'rotate-180' : ''}`}>{'\u25BC'}</span>
          </button>

          {showAdvanced && (
            <div className="space-y-4 mb-4 p-4 rounded-lg border border-gray-700 bg-gray-800 bg-opacity-50">
              {/* Tone */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Voice & Tone</label>
                <div className="grid grid-cols-3 gap-1.5">
                  {TONES.map((t) => (
                    <button key={t.id} className={`py-2 px-2 rounded-lg text-xs font-medium transition-all ${tone === t.id ? 'bg-blue-600 text-white border border-blue-500' : 'bg-gray-900 text-gray-400 border border-gray-700 hover:border-gray-500'}`} onClick={() => setTone(t.id)}>
                      <div className="font-semibold">{t.label}</div>
                      <div className="opacity-70 mt-0.5">{t.desc}</div>
                    </button>
                  ))}
                </div>
              </div>
              {/* CTA */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Call-to-Action Style</label>
                <div className="grid grid-cols-3 gap-1.5">
                  {CTA_TYPES.map((c) => (
                    <button key={c.id} className={`py-2 px-2 rounded-lg text-xs font-medium transition-all ${ctaType === c.id ? 'bg-blue-600 text-white border border-blue-500' : 'bg-gray-900 text-gray-400 border border-gray-700 hover:border-gray-500'}`} onClick={() => setCtaType(c.id)}>
                      <div className="font-semibold">{c.label}</div>
                      <div className="opacity-70 mt-0.5">{c.desc}</div>
                    </button>
                  ))}
                </div>
              </div>
              {/* Formatting */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Formatting Style</label>
                <div className="grid grid-cols-3 gap-1.5">
                  {FORMAT_OPTS.map((f) => (
                    <button key={f.id} className={`py-2 px-2 rounded-lg text-xs font-medium transition-all ${formatting === f.id ? 'bg-blue-600 text-white border border-blue-500' : 'bg-gray-900 text-gray-400 border border-gray-700 hover:border-gray-500'}`} onClick={() => setFormatting(f.id)}>
                      <div className="font-semibold">{f.label}</div>
                      <div className="opacity-70 mt-0.5">{f.desc}</div>
                    </button>
                  ))}
                </div>
              </div>
              {/* Emoji */}
              <div className="flex items-center justify-between">
                <label className="text-sm font-medium text-gray-300">Use Emojis</label>
                <button className={`relative w-11 h-6 rounded-full transition-all ${useEmoji ? 'bg-blue-600' : 'bg-gray-700'}`} onClick={() => setUseEmoji(!useEmoji)}>
                  <div className={`absolute top-0.5 w-5 h-5 rounded-full bg-white transition-all ${useEmoji ? 'left-5' : 'left-0.5'}`} />
                </button>
              </div>
              {/* Keywords */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">Keywords <span className="text-gray-500">(comma-separated)</span></label>
                <input className="input-field" placeholder="e.g., locum tenens, physician shortage, staffing ROI" value={keywords} onChange={(e) => setKeywords(e.target.value)} />
              </div>
              {/* Key Phrases */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">Key Phrases to Include</label>
                <textarea className="input-field" placeholder="e.g., proactive beats reactive&#10;coverage risk calendar" value={keyPhrases} onChange={(e) => setKeyPhrases(e.target.value)} rows={3} />
              </div>
              {/* Avoid */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">Topics to Avoid</label>
                <input className="input-field" placeholder="e.g., politics, specific competitors" value={avoidTopics} onChange={(e) => setAvoidTopics(e.target.value)} />
              </div>
            </div>
          )}

          {/* Image options — schedule overrides per-slot */}
          <label className="block text-sm font-medium text-gray-300 mb-1">
            Image Style
            {brand.schedule && brand.schedule.length > 0 && (
              <span className="text-xs text-amber-300 font-normal ml-2">(schedule overrides — each slot uses its own image system A/B/C)</span>
            )}
          </label>
          <div className="grid grid-cols-3 gap-2 mb-3">
            {IMAGE_STYLES.map((s) => {
              const isLocked = !!(brand.schedule && brand.schedule.length > 0);
              return (
                <button
                  key={s.id}
                  className={`p-2.5 rounded-lg text-center transition-all ${imageStyle === s.id ? 'bg-blue-600 border-blue-500 border' : 'bg-gray-800 border border-gray-600 hover:border-gray-500'} ${isLocked ? 'opacity-50 cursor-not-allowed' : ''}`}
                  onClick={() => { if (!isLocked) setImageStyle(s.id); }}
                  disabled={isLocked}
                  title={isLocked ? 'Image system is set per slot by the schedule' : ''}
                >
                  <div className="text-sm font-semibold">{s.l}</div>
                  <div className="text-xs text-gray-400 mt-0.5">{s.d}</div>
                </button>
              );
            })}
          </div>

          <label className="block text-sm font-medium text-gray-300 mb-1">
            {brand.schedule && brand.schedule.length > 0
              ? `Image Generation (${brand.schedule.length} cards across ${new Set(brand.schedule.map((s2) => s2.day)).size} days, schedule-driven)`
              : `Image Generation (${POSTS_PER_DAY} posts × ${WEEKDAYS.length} weekdays = ${IMAGE_COUNT} branded cards)`}</label>
          <div className="mb-4 px-3 py-2 rounded-lg bg-gray-800 border border-gray-600 text-gray-300 text-sm">
            <span className="font-semibold">{'\uD83C\uDFA8'} Branded Cards</span>
            <span className="text-xs opacity-70 ml-2">Canvas-based, instant, on-brand</span>
          </div>

          {/* Statics bank — evergreen fallback buffer */}
          <button
            className="btn-secondary w-full mb-3 text-sm flex items-center justify-center gap-2"
            onClick={generateStaticsBank}
            disabled={loading || imgLoading || bankLoading}
            title="Batch-generate 8 evergreen posts to Saved — your fallback buffer for weeks when the build doesn't happen"
          >
            {bankLoading ? (<><span className="spinner" /> {genPhase || 'Filling bank...'}</>) : (<>{'🗃'} Fill Statics Bank (8 evergreen posts)</>)}
          </button>

          {/* Generate button */}
          <button className="btn-primary w-full py-3 text-lg flex items-center justify-center gap-2" onClick={generate} disabled={loading || imgLoading || bankLoading}>
            {loading ? (
              <><span className="spinner" /> {genPhase || 'Generating...'}</>
            ) : imgLoading ? (
              <><span className="spinner" /> {imgProgress || 'Generating images...'}</>
            ) : (
              <>{'\u26A1'} {(() => {
                const total = brand.schedule && brand.schedule.length > 0 ? brand.schedule.length : IMAGE_COUNT;
                // Day range derived from schedule slots (Mon-Fri if any Friday slot exists, else Mon-Thu).
                const sched = brand.schedule || [];
                const dayRange = sched.some((s) => s.day === 'Friday') ? 'Mon-Fri' : (sched.length > 0 ? 'Mon-Thu' : 'Mon-Fri');
                return autoTrending && live
                  ? `Find Trend + Fill ${dayRange} (${total} Posts)`
                  : `Generate Full Week (${total} Posts, ${dayRange})`;
              })()}</>
            )}
          </button>
          {error && <p className="text-red-400 text-sm mt-2">Error: {error}</p>}
        </div>

        {/* Data points */}
        {brand.dataPoints?.length > 0 && (
          <div className="card p-4">
            <h3 className="text-sm font-semibold text-gray-300 mb-2">{'\uD83D\uDCCB'} Available Data Points</h3>
            <div className="space-y-1">
              {brand.dataPoints.map((dp, i) => (
                <div key={i} className="text-xs text-gray-400 flex items-start gap-2">
                  <span className="text-blue-400 mt-0.5">{'\u2192'}</span>{dp}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* ═══════════ RIGHT: OUTPUT ═══════════ */}
      <div className="space-y-4">
        {/* Post preview */}
        <div className="card p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-bold text-white">
              {platform} Post Preview
              {posts.length > 1 && <span className="text-sm font-normal text-gray-400 ml-2">(Post {selectedImg + 1} of {posts.length})</span>}
            </h2>
            {post && (
              <div className="flex gap-2">
                <button className="btn-secondary text-sm" onClick={() => { navigator.clipboard.writeText(post); showToast('Post copied!'); }}>{'\uD83D\uDCCB'} Copy</button>
                <button className="btn-secondary text-sm" onClick={savePost}>{'\uD83D\uDCBE'} Save</button>
                <button className="btn-ghost text-sm" onClick={generate} disabled={loading || imgLoading}>{'\uD83D\uDD04'}</button>
              </div>
            )}
          </div>

          {/* Trending topic badge */}
          {post && selectedTrending && (
            <div className="mb-3 p-2.5 rounded-lg bg-indigo-900 bg-opacity-30 border border-indigo-800">
              <div className="flex items-center gap-2 text-xs">
                <span className="text-indigo-400 font-semibold">{'\uD83D\uDD25'} Based on trending:</span>
                <span className="text-indigo-300">{selectedTrending.topic}</span>
              </div>
            </div>
          )}

          {post ? (
            <div className="bg-white rounded-lg p-5 text-gray-800 text-sm leading-relaxed" style={{ maxHeight: 500, overflowY: 'auto' }}>
              <div className="flex items-center gap-3 mb-4 pb-3 border-b border-gray-200">
                <div className="w-11 h-11 rounded-full flex items-center justify-center text-white font-bold text-lg" style={{ background: brand.colors.primary }}>
                  {(brand.name || 'B')[0]}
                </div>
                <div>
                  <div className="font-bold text-gray-900">{brand.name || 'Your Brand'}</div>
                  <div className="text-xs text-gray-500">{brand.tagline || ''}</div>
                </div>
              </div>
              <FormattedPost text={post} />
              <div className="flex gap-2 mt-4 pt-3 border-t border-gray-200 flex-wrap">
                <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full font-medium">{tone}</span>
                <span className="text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full font-medium">CTA: {ctaType}</span>
                <span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full font-medium">{formatting}</span>
                {selectedTrending && <span className="text-xs bg-red-100 text-red-600 px-2 py-0.5 rounded-full font-medium">{'\uD83D\uDD25'} Trending</span>}
              </div>
            </div>
          ) : (
            <div className="text-center py-16 text-gray-500">
              <div className="text-4xl mb-3">{'\u270D\uFE0F'}</div>
              <p>Your generated post will appear here</p>
              <p className="text-sm mt-1">{live ? (autoTrending ? `AI will find a trend + write ${IMAGE_COUNT} posts` : `Live AI mode \u2014 ${IMAGE_COUNT} posts per click`) : 'Demo mode \u2014 add API key for live AI'}</p>
            </div>
          )}
        </div>

        {/* Image gallery */}
        <div className="card p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-bold text-white">
              {'\uD83D\uDDBC'} Images
              {successfulImages.length > 0 && <span className="text-sm font-normal text-gray-400 ml-2">({successfulImages.length}/{IMAGE_COUNT})</span>}
            </h2>
            {successfulImages.length > 0 && (
              <div className="flex gap-2">
                <button className="btn-secondary text-sm" onClick={downloadAll}>{'\u2B07\uFE0F'} All</button>
              </div>
            )}
          </div>

          <canvas ref={cvRef} style={{ display: 'none' }} />

          {imgLoading ? (
            <div className="text-center py-14 text-gray-500">
              <div className="spinner mx-auto mb-4" style={{ width: 40, height: 40 }} />
              <p className="font-medium text-gray-300">{imgProgress || 'Generating images...'}</p>
              <p className="text-sm mt-1">Generating {IMAGE_COUNT} posts across Mon-Fri and rendering paired cards</p>
              <div className="flex justify-center gap-2 mt-4">
                {Array.from({ length: IMAGE_COUNT }).map((_, i) => (
                  <div key={i} className={`w-3 h-3 rounded-full transition-all ${
                    imgProgress.includes(`${i + 1}`) ? 'bg-blue-500 animate-pulse' :
                    imgProgress.includes(`${i + 2}`) || imgProgress.includes('Analyzing') ? 'bg-gray-600' : 'bg-green-500'
                  }`} />
                ))}
              </div>
            </div>
          ) : (successfulImages.length > 0 || images.some((i) => i && i.textOnly)) ? (
            <div>
              <div className="relative mb-3">
                {images[selectedImg]?.url ? (
                  <>
                    <img src={images[selectedImg].url} className="w-full rounded-lg shadow-lg" alt={`Generated image ${selectedImg + 1}`} onError={() => { showToast('Image load error'); const updated = [...images]; updated[selectedImg] = { ...updated[selectedImg], url: null, error: 'Load failed' }; setImages(updated); }} />
                    <div className="absolute top-2 left-2 badge bg-black bg-opacity-60 text-white text-xs px-2 py-1">{selectedImg + 1} / {images.length}</div>
                    <button className="absolute top-2 right-2 btn-secondary text-xs" onClick={() => downloadImage(images[selectedImg], selectedImg)}>{'\u2B07\uFE0F'}</button>
                  </>
                ) : images[selectedImg]?.textOnly ? (
                  <div className="w-full rounded-lg bg-amber-900/30 border border-amber-700/40 p-8 text-center">
                    <div className="text-amber-300 text-sm font-bold tracking-wider mb-1">TEXT-ONLY POST</div>
                    <div className="text-amber-200/70 text-xs">Friday attention posts are text-only by design. No card image.</div>
                    <div className="text-amber-200/50 text-xs mt-2">{selectedImg + 1} of {images.length}</div>
                  </div>
                ) : null}
              </div>
              <div className="grid grid-cols-5 gap-2">
                {images.map((img, i) => {
                  const isTextOnly = img && img.textOnly;
                  const hasUrl = img && img.url;
                  const clickable = hasUrl || isTextOnly;
                  return (
                    <button
                      key={i}
                      className={`relative rounded-lg overflow-hidden border-2 transition-all aspect-video ${selectedImg === i ? 'border-blue-500 shadow-lg shadow-blue-500/20' : 'border-gray-600 hover:border-gray-400'} ${!clickable ? 'opacity-40' : ''}`}
                      onClick={() => clickable && setSelectedImg(i)}
                      disabled={!clickable}
                      title={isTextOnly ? 'Text-only post (no card)' : undefined}
                    >
                      {hasUrl ? (
                        <img src={img.url} className="w-full h-full object-cover" alt={`Thumb ${i + 1}`} />
                      ) : isTextOnly ? (
                        <div className="w-full h-full bg-amber-900/40 flex flex-col items-center justify-center text-amber-300">
                          <div className="text-xs font-bold tracking-wider">TEXT</div>
                          <div className="text-[10px] opacity-70">no card</div>
                        </div>
                      ) : (
                        <div className="w-full h-full bg-gray-800 flex items-center justify-center text-xs text-red-400">{'\u2717'}</div>
                      )}
                      <div className="absolute bottom-0 left-0 right-0 bg-black bg-opacity-50 text-white text-xs text-center py-0.5">{i + 1}</div>
                    </button>
                  );
                })}
              </div>
              {images[selectedImg]?.prompt && (
                <div className="mt-3 p-2 bg-gray-800 rounded-lg">
                  <p className="text-xs text-gray-400 truncate" title={images[selectedImg].prompt}>{'\uD83C\uDFA8'} {images[selectedImg].prompt}</p>
                  {images[selectedImg]?.model && <p className="text-xs text-gray-500 mt-0.5">Model: {images[selectedImg].model}</p>}
                </div>
              )}
            </div>
          ) : (
            <div className="text-center py-12 text-gray-500">
              <div className="text-4xl mb-3">{'\uD83D\uDDBC'}</div>
              <p>{IMAGE_COUNT} unique images will be generated with your post</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
