export const MOCK_POSTS = {
  linkedin: {
    'Workforce Insights': [
      "The numbers don't lie.\n\nEvery unfilled physician position costs your hospital $1M+ per year.\n\nThat's not a budget line item. That's lost billings. Diverted patients. Overtime premiums that never stop.\n\nBut here's what keeps me up at night:\n\nMost hospital leaders don't calculate this cost until the gap already exists.\n\nBy then, you're in reactive mode. Paying premium rates. Scrambling for coverage.\n\nThe math is simple:\n\u2192 Proactive coverage planning = lower cost per physician\n\u2192 Reactive scrambling = highest cost per physician\n\nYour workforce strategy isn't a staffing problem.\nIt's a revenue problem.\n\nWhat's the real cost of your current coverage gaps?\n\n#PhysicianWorkforce #HealthcareLeadership #HospitalAdministration #WorkforceStrategy",
      "86,000.\n\nThat's the projected U.S. physician shortage by 2036.\n\nAnd here's the part nobody's talking about:\n\nThe shortage isn't evenly distributed.\n\nRural hospitals face a 60% projected shortfall. Urban hospitals? 10%.\n\nThat means if you're running a community hospital outside a major metro area \u2014 you're competing for talent with one hand tied behind your back.\n\nThe physicians aren't coming. Not fast enough.\n\nSo the question isn't \"will we have gaps?\"\n\nIt's \"how are we covering them before they become crises?\"\n\nThe health systems that figure this out first will win.\n\n#PhysicianShortage #RuralHealthcare #WorkforcePlanning #HealthcareStrategy",
    ],
    'Physician Lifestyle': [
      "You didn't go through 12+ years of training to feel trapped.\n\nBut that's exactly how it feels for a lot of physicians right now.\n\nThe burnout. The admin burden. The golden handcuffs of a contract that looked great on paper but left you with zero flexibility.\n\nHere's what I'm hearing from physicians every week:\n\n\"I love medicine. I just don't love this job anymore.\"\n\nLocum tenens isn't a backup plan. For a growing number of physicians, it's the path back to actually practicing medicine.\n\n\u2192 Choose your schedule\n\u2192 Pick your locations\n\u2192 Focus on patients, not politics\n\nThe model is changing. The physicians who see it first are already moving.\n\nAre you one of them?\n\n#LocumTenens #PhysicianLife #PhysicianBurnout #MedicalCareers",
    ],
    'Staffing Strategy': [
      "Your staffing problem isn't a staffing problem.\n\nIt's a timing problem.\n\nEvery hospital knows physicians retire. Every hospital knows recruitment takes 6-12 months. Every hospital has seen seasonal volume surges.\n\nBut most hospitals react to these events instead of planning for them.\n\nThe result?\n\u2192 Higher locum rates (because your urgency is visible)\n\u2192 Coverage gaps that disrupt patient care\n\u2192 Burnt out staff picking up the slack\n\u2192 Revenue walking out the door\n\nThe fix is a 5-step proactive model:\n\n1. Build a coverage risk calendar\n2. Define your highest-risk specialties\n3. Establish a locum partner before you need one\n4. Credential physicians in advance\n5. Integrate locums into your care culture\n\nProactive staffing costs less than reactive staffing.\nEvery. Single. Time.\n\n#StaffingStrategy #HealthcareOperations #PhysicianRecruitment #HospitalManagement",
      "A strong locum tenens strategy is not a backup plan.\n\nIt's a competitive advantage.\n\nReactive staffing model:\n\u2192 You call when you're desperate\n\u2192 Agencies know you're desperate\n\u2192 You pay desperate rates\n\nProactive staffing model:\n\u2192 Your locum partner knows your facility\n\u2192 Physicians are pre-credentialed\n\u2192 Coverage deploys in days, not weeks\n\u2192 Cost is planned, not panic-priced\n\nThe hospitals winning the workforce game in 2026 aren't the ones with the biggest recruitment budgets.\n\nThey're the ones who stopped treating coverage as an emergency and started treating it as infrastructure.\n\n#LocumTenens #HospitalStrategy #PhysicianCoverage #HealthcareLeadership",
    ],
    'Industry Commentary': [
      "The 2026 Match was the largest in history.\n\n41,482 positions filled.\n\nBut before we celebrate \u2014 look at what's still broken:\n\n\u2192 Emergency medicine: unfilled positions rising\n\u2192 Psychiatry: demand outpacing supply 3:1\n\u2192 Rural programs: still struggling to attract candidates\n\u2192 Anesthesiology and radiology: persistent gaps\n\nMore matches doesn't mean the shortage is over.\n\nThe Match fills residency slots. It doesn't fix the 86,000 physician deficit projected for 2036.\n\nIt goes down when hospitals, health systems, and staffing partners build real workforce infrastructure.\n\nNot hope. Infrastructure.\n\n#Match2026 #MedicalEducation #PhysicianWorkforce #HealthcarePolicy",
    ],
    'Lead Magnet': [
      "Every week I talk to hospital administrators who tell me the same thing:\n\n\"We knew the gap was coming. We just didn't move fast enough.\"\n\nThat's why we built the free Physician Coverage Planning Guide.\n\nInside you'll find:\n\u2192 The 5-step proactive coverage framework\n\u2192 Cost calculator: what unfilled positions actually cost you\n\u2192 Specialty risk matrix for 2026-2028\n\u2192 Credentialing timeline templates\n\u2192 Locum integration best practices\n\nDM me \"GUIDE\" or comment below and I'll send it over.\n\nBecause the best time to plan for a coverage gap is before it exists.\n\n#PhysicianStaffing #HealthcareResources #HospitalLeadership #FreeGuide",
    ],
    'Educational': [
      "Here's something most people get wrong:\n\nThey think more content = more leads.\n\nThe data tells a different story.\n\nThe highest-converting LinkedIn profiles post 4x per week. Not 14. Not 7. Four.\n\n\u2192 Consistency beats volume\n\u2192 Each post has time to gain traction\n\u2192 Quality stays high when quantity stays reasonable\n\nThe 4-3-2-1 framework:\n4 posts per week\n3 content types\n2 audiences\n1 lead magnet post\n\nSimple. Repeatable. Scalable.\n\n#ContentStrategy #LinkedInGrowth #LeadGeneration",
    ],
    'Storytelling': [
      "Last month, a hospital CEO told me something I haven't stopped thinking about.\n\n\"We lost our only cardiologist to retirement. We knew it was coming for two years. We still weren't ready.\"\n\nTwo years of warning.\nSix months with no coverage.\nPatients diverted to a hospital 90 minutes away.\n\nThis isn't a staffing failure. It's a systems failure.\n\nThe difference between hospitals that handle physician transitions smoothly and those that scramble?\n\nA plan. Not a hope.\n\nA plan with pre-credentialed physicians, coverage calendars, and a partner who already knows your facility.\n\nEvery hospital will face this moment. The only question is whether you'll be ready.\n\n#HealthcareLeadership #PhysicianRecruitment #WorkforcePlanning",
    ],
  },
  facebook: {
    'Workforce Insights': [
      "Did you know? Every unfilled physician position costs hospitals over $1 MILLION per year.\n\nThat's not just a number \u2014 it's lost patient care, burnt-out staff, and revenue that never comes back.\n\nWith 86,000 physicians projected to be short by 2036, the time to plan is NOW.\n\nHere's what smart hospital leaders are doing differently:\n- Building coverage risk calendars\n- Pre-credentialing locum physicians\n- Planning 12-18 months ahead, not 12-18 days\n\nProactive beats reactive. Every time.\n\n#HealthcareWorkforce #PhysicianShortage #HospitalManagement",
    ],
    'Staffing Strategy': [
      "Here's the truth about physician staffing that nobody wants to hear:\n\nIf you're calling for coverage when you already have a gap \u2014 you're already too late.\n\nRetirement waves. Unexpected departures. Seasonal surges. Recruitment that takes 6-12 months.\n\nAll four are predictable. None of them have to catch you off guard.\n\n5 steps to get ahead:\n1. Build a coverage risk calendar\n2. Identify your highest-risk specialties\n3. Partner with a locum firm BEFORE you need one\n4. Credential physicians in advance\n5. Integrate locums into your care culture\n\n#StaffingStrategy #HealthcareLeadership #LocumTenens",
    ],
  },
};
