export const STEADFAST_PRESET = {
  name: 'Steadfast Physician Partners',
  tagline: 'Reliable Physician Coverage. Deployed Fast.',
  category: 'The company that helps hospitals eliminate physician coverage gaps before they become crises.',
  colors: {
    primary: '#1a365d',
    secondary: '#2c5282',
    accent: '#3182ce',
    light: '#bee3f8',
    bg: '#1a365d',
    text: '#ffffff',
  },
  pillars: [
    { name: 'Workforce Insights', audience: 'Hospital Leaders', description: 'Data-driven content about physician shortages and capacity gaps. Default framework PASS, hooks Bold Stat or Reframe.' },
    { name: 'Physician Lifestyle', audience: 'Physicians', description: 'Content for physicians considering locum work and career flexibility. Default framework SLAY, hooks Direct Question, Story Opener, Bold Stat.' },
    { name: 'Staffing Strategy', audience: 'Hospital Leaders', description: 'Proactive staffing frameworks, cost analysis, and locum strategy. Default framework PASS or SLAY, hooks Contrarian Claim or POV Scenario.' },
    { name: 'Industry Commentary', audience: 'Both', description: 'Hot takes on healthcare policy, Match results, market shifts. Default framework SLAY adapted, hook Reframe.' },
    { name: 'Lead Magnet', audience: 'Hospital Leaders', description: 'Soft introduction to the offer. Thursday 5:15 PM slot. Hooks Story Opener or Direct Question. Link in comments, never in caption.' },
  ],
  schedule: [
    { day: 'Monday', time: '7:30 AM', pillar: 'Physician Lifestyle', audience: 'Physicians', imageStyle: 'stat' },
    { day: 'Monday', time: '12:00 PM', pillar: 'Workforce Insights', audience: 'Hospital Leaders', imageStyle: 'quote' },
    { day: 'Tuesday', time: '7:30 AM', pillar: 'Industry Commentary', audience: 'Both', imageStyle: 'stat' },
    { day: 'Tuesday', time: '12:00 PM', pillar: 'Workforce Insights', audience: 'Hospital Leaders', imageStyle: 'multi' },
    { day: 'Wednesday', time: '7:30 AM', pillar: 'Physician Lifestyle', audience: 'Physicians', imageStyle: 'quote' },
    { day: 'Wednesday', time: '12:00 PM', pillar: 'Staffing Strategy', audience: 'Hospital Leaders', imageStyle: 'stat' },
    { day: 'Thursday', time: '12:00 PM', pillar: 'Staffing Strategy', audience: 'Hospital Leaders', imageStyle: 'multi' },
    { day: 'Thursday', time: '5:15 PM', pillar: 'Lead Magnet', audience: 'Hospital Leaders', imageStyle: 'stat' },
  ],
  dataPoints: [
    '86,000 projected physician shortage by 2036',
    '65% of hospitals have run below capacity due to staffing shortages',
    'Rural hospitals face 60% projected physician shortage vs 10% urban',
    '$1M+ lost annually per unfilled physician position',
    'Average permanent physician search takes 6-12 months',
    '40% of hospital leaders already use locum tenens to address demand spikes',
    '2026 Match: largest in history with 41,482 positions filled',
    'Resident Physician Shortage Reduction Act would add 14,000 residency slots over 7 years',
  ],
};
